name: lectarium
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  localstorage: ^4.0.0+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  stacked: ^2.3.12
  responsive_builder: ^0.1.4
  provider: ^6.0.3
  logger: ^1.1.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  simple_animations: ^4.2.0
  dio: ^4.0.6
  flutter_blurhash: ^0.7.0
  # file_picker: ^2.1.6
  image_picker: ^0.8.5+3
  octo_image: ^1.0.2
  smart_select: ^4.3.2
  flutter_svg: ^1.0.3
  percent_indicator: ^4.2.1
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  sizer: ^1.1.7
  sizer_mod: ^0.0.1
dev_dependencies:
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SuisseIntl
      fonts:
        - asset: assets/fonts/Suisse.ttf
        - asset: assets/fonts/Suisse.woff
        - asset: assets/fonts/Suisse.woff2
        - asset: assets/fonts/Suisse.eot
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
