name: lectarium
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  localstorage: ^3.0.6+9
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider_architecture: ^1.0.3
  responsive_builder: ^0.1.4
  provider: ^4.3.3
  logger: ^0.7.0+2
  get_it: ^3.0.3
  equatable: ^1.0.1
  simple_animations: ^2.5.1
  page_transition: "^1.1.7+6"
  dio: ^3.0.10
  flutter_blurhash: ^0.5.0
  # file_picker: ^2.1.6
  image_picker: ^0.6.7+22
  octo_image: ^0.3.0
  curved_navigation_bar: ^0.3.7
  smart_select: ^4.3.2
  flutter_keyboard_visibility: ^4.0.6
  flutter_svg: ^1.0.3
  loader_overlay: ^2.0.7
  percent_indicator: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
